services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - backend_network
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - backend_network
    depends_on:
      - postgres


  auth-service:
    container_name: "auth-service"
    build: ./auth-service
    ports:
      - "8085:8085"
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres
    networks:
      - backend_network


  postgres:
    image: postgres:15
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes_db

    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge